### ISSUE TITLE
1.0.0-alpha-3 checklist

### ISSUE THREAD

**Issue by terrysahaidak** [terrysahaidak/GitterMobile#41]
- [x] Basic activity
- [x] Receive messages from snapshot
- [x] Message screen; read by
- [ ] Automatically read all messages #40
- [ ] Settings screen
- [ ] Save last room and navigate to it after restart
- [x] Reconnect to faye server if app is on focus
- [x] Fix message resending
- [x] Fix double message after relogin
