### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by terrysahaidak** [terrysahaidak/GitterMobile#5]
# Roadmap

If you have the feature request, just drop the line here.
# Features
- [x] Home screen
- [x] Basic drawer #1 
- [x] Realtime updates for drawer #4 
- [x] Room messages list screen #7 
- [x] Send message #7 
- [x] Base mark as read #44  
- [x] Edit message #7
- [x] Delete messages #7 
- [x] Realtime messages updates #12 
- [x] Parsing messages to display mention and links, emoji #24 
- [x] Collapsing messages #25 
- [x] Status (`/me`) messages type #25 
- [x] Search rooms and peoples #26 
- [x] Favorite/unfavorite room
- [ ] Redux store (ability to restore all the redux state from the AsyncStorage)
- [ ] Parsing messages to display PR/issues, some embedded content (tweets, images)
- [x] Search messages #53 
- [ ] New drawer styles
- [x] User info screen #30 
- [x] Room info screen #34 
- [ ] Push-notifications
- [x] Authentication screen (while fetching data)
- [x] Single Navigator #21 
- [ ] Ability to create new rooms
- [ ] Ability to upload images
- [ ] Better code documentation
- [ ] Tests
- [ ] Forwarded messages
- [ ] Offline support
- [ ] Error handling
- [x] IRC commands #47 
- [ ] Autosuggesting for mentions, commands #65 
- [ ] Favorite messages
- [ ] CodePush for updates
- [x] Sharing ability and screens
- [x] Room activity feed #38 
- [x] Message screen #38 
- [ ] Add emoji bar #64 
- [ ] Deep linking #74 
- [ ] Users' online status
- [ ] Add all the room settings #58 
- [ ] Styling activity feed #104
- [ ] Upload images #73 
- [ ] Save input text draft per room
