### ISSUE TITLE
v0.6

### ISSUE THREAD

**Issue by terrysahaidak** [terrysahaidak/GitterMobile#90]
- [x] Wait until https://github.com/facebook/react-native/pull/13532 will be merged or use my fork (using extendedListView #110)
- [x] Fix persist taps in room screen
- [x] Refactor the app with new structure
- [x] Use some new navigation library #93 
- [x] Fix some missing icons
- [ ] Add fully featured markdown support #114 
- [ ] Use browser faye client instead of native modules
- [x] Fix status bar issues #93 
- [x] Do not bundle all the emojis with the app. Use from the network instead.
- [x] Upgrade to latest RN version
- [x] Use vector icons
- [x] Fix iOS layout bugs 
- [x] Fix drawer layout lags in android https://github.com/terrysahaidak/GitterMobile/pull/91
- [x] Add Scroll To Bottom button #103 
- [x] Fix Chat privately button #99 
- [x] Fix Twitter user profile screen #97 
- [x] Fix room more messages spinner #100 
- [x] Add image modal #111
- [x] Add new login screens #110
- [x] Save input state as draft #112 
- [x] Add ability to cancel editing message. Improve editing process #113

**Comment by dikiaap** [comment]
What about beta release?

**Comment by XAOLER** [comment]
What you mean ?


2017-06-17 12:35 GMT+03:00 Diki Ananta <notifications@github.com>:

**Comment by terrysahaidak** [comment]
@dikiaap just build and posted beta release https://github.com/JSSolutions/GitterMobile/releases/tag/v0.6.0-beta-1

It's still not production-ready, but it's our goal to make it fully featured Gitter client.
